### ISSUE TITLE
Remove addReturnValueHandlers() method

### ISSUE THREAD

**Issue by rstoyanchev** [sdeleuze/spring-backbone-todo#1]
Great example, nice and short. It could be even shorter in WebConfig the addReturnValueHandlers() overridden method can be removed.

**Comment by sdeleuze** [comment]
I have just fixed this issue and upgraded Spring to 3.1.0.RELEASE.

I order to make it even shorter, do you know if I could configure the "/api" prefix at controler or application level in order to be DRY compliant ?

**Comment by rstoyanchev** [comment]
Yes, you can add a type-level @RequestMapping annotation:

``` java
@RequestMapping("/api")
@Controller
public class TodoController {

    @RequestMapping( value = "/todo/{id}",method = RequestMethod.GET )
    @ResponseBody
    public final Todo get( @PathVariable( "id" ) final String id ){
        // ...
    }
}
```

**Comment by sdeleuze** [comment]
Thanks
